language: ruby
rvm:
  - "2.0.0"
  - "rbx-2.2.1"
  - "rbx-2.1.1"
matrix:
  allow_failures:
    - rvm: "rbx-2.2.1"
    - rvm: "rbx-2.1.1"
cache:
  - apt
before_install:
  - bundle install --path=vendor/bundle
  - sudo apt-get install p7zip-full
install: bundle exec rake build_local
script: bundle exec rspec spec/seven_zip_ruby_spec.rb
